/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg.oct12.batch3.hibernate.labbook;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
